version: "3.9"

services:
  api:
    image: test-task-forager-ai
    container_name: test-task-forager-ai-api
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres-db
    volumes:
      - ".:/api"
      - "./api:/apps"
    networks:
      - test-task-forager-ai

  postgres-db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      test-task-forager-ai:
        # Have access the database using pgadmin4
        ipv4_address: 145.24.0.6

  pgadmin4:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "5050:5050"
    networks:
      - test-task-forager-ai

volumes:
  data:

networks:
  test-task-forager-ai:
    ipam:
      driver: default
      config:
        - subnet: 145.24.0.0/24
